### ISSUE TITLE
Typescript: Add React.Component to SideNavigationItem label type

### ISSUE THREAD

**Issue by aureldent** [lumapps/design-system#344]
[DISCUSSION]
As I use the SideNavigation, I want to put in each of the SideNavigationItem a custom Component used to handle translation in my app (similar to react-intl). It has to be a component because it's a consumer of a provider, providing the translations for the app.

An so I open this issue to **discuss the idea to add React.Component as an additonnal type on the label of a SideNavigationItem**. All of this is only to avoid putting a //@ts-ignore but may be usefull for other people.

It may also be worth keeping in mind that kind of thing for other components with labels or when restricting the way to use a component.

https://github.com/lumapps/design-system/blob/master/packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx

**Comment by gcornut** [comment]
You can do a PR if you want. But use the type `ReactNode`, it contains `string` and JSX elements

**Comment by gcornut** [comment]
See https://github.com/lumapps/design-system/pull/345
