### ISSUE TITLE
[site-demo] wrong color hex code for material theme

### ISSUE THREAD

**Issue by FlorentDinet** [lumapps/design-system#390]
DemoColor block doesn't retrieve the right color hex code for material theme

<img width="288" alt="Capture d’écran 2020-05-06 à 10 34 56" src="https://user-images.githubusercontent.com/15898440/81155504-4e948500-8f85-11ea-947c-d40088dd70c4.png">

**Comment by gcornut** [comment]
Resolved in v0.24.0
