### ISSUE TITLE
[Doc] Some bugs in the documentation

### ISSUE THREAD

**Issue by aureldent** [lumapps/design-system#525]
First, the new version of the doc is great !

I just noted some bug/weird behaviors on some pages:

- https://design.lumapps.com/product/components/progress-tracker/ => is lacking properties
- https://design.lumapps.com/product/components/popover/ => When scrolling there is a weird bouncing effect

**Comment by matmkian** [comment]
Will be fixed in the next version of the demo site (using Gatsby) -> should be deployed next week
