### ISSUE TITLE
Documentation for AngularJS version

### ISSUE THREAD

**Issue by tinyCoder32** [lumapps/design-system#663]
Hi, thanks for the amazing project. Been a long-time follower for the old angularjs version on https://ui.lumapps.com, but with the poor support on that project I searched and found this one, seems most of the components been updated and new ones added, I am very excited to update the version I have, but I couldn't find any documentation for the AngularJS version.

The docs on https://design.lumapps.com seems for React, I appreciate your kind help.

**Comment by gcornut** [comment]
The AngularJS version is deprecated, it won't receive update and we plan to remove it when we have migrated everything to React
