### ISSUE TITLE
Composant DatePicker

### ISSUE THREAD

**Issue by Digiwin44** [lumapps/design-system#894]
Bonjour,

L'attribut locale du composant "DatePickerField" n'est pas pris en compte. En lui passant FR, les dates sont toujours au format anglais.
`                <DatePickerField
                  locale="fr"
                  label="Pick a date"
                  value={new Date()}
                  onChange={setDatePicked}
                  nextButtonProps={{ label: 'Next month' }}
                  previousButtonProps={{ label: 'Previous month' }}
              />`
<img width="184" alt="image" src="https://user-images.githubusercontent.com/99723935/196734654-e30c2c83-5364-432a-a6dd-2ef3af249a5f.png">

**Comment by alexandra-klr** [comment]
Bonjour @Digiwin44,

Pourriez-vous me fournir une page sur laquelle se trouve ce composant svp ?

**Comment by Digiwin44** [comment]
Bonjour,

vous trouverez un lien ici : https://csbx-eu.lumapps.com/a/ratp-dev/home/business-applications/conser puis sur le lien « Consulter mes déclarations »

**Comment by alexandra-klr** [comment]
Merci.
Je ne vois pas de souci sur ce composant. Il reprend bien la langue de l'interface.
Si l'interface est en anglais, il affiche la date en anglais. 
Si vous passez l'interface en français, la date est bien en français.

[ConSer - Intranet.webm](https://user-images.githubusercontent.com/91319191/198542148-4d21fb52-90c3-432b-ba89-c57ebed2153c.webm)
